owner: Zerio-AB
repo: status-page

sites:
  - name: Zerio Main Site
    url: https://zerio.se
  - name: Zerio Restaurant Site
    url: https://restaurant.zerio.se
  - name: Zerio Restaurant API
    url: https://restaurant.zerio.se/api/health

status-website:
  cname: status.zerio.se
  logoUrl: https://zerio.se/logo.png
  name:
  introTitle: "Här kan du se aktuell status för samtliga av våra hemsidor och API:er"
  introMessage:
  footer:
    - title: Zerio
      href: https://zerio.se
    - title: Zerio Restaurant
      href: https://restaurant.zerio.se
    - title: Zerio Restaurant API
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
